# Generated by Django 5.2 on 2025-05-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='history_images/'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='search_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=5),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='query',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
